ALTER TABLE user_tracking ADD COLUMN IF NOT EXISTS os VARCHAR(255);
ALTER TABLE user_tracking ADD COLUMN IF NOT EXISTS os_version VARCHAR(255);
ALTER TABLE user_tracking ADD COLUMN IF NOT EXISTS ip_address VARCHAR(255);
