ALTER TABLE hotels ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE hotels ADD CONSTRAINT IF NOT EXISTS hotels_slug_unique UNIQUE(slug);

ALTER TABLE hotels ADD COLUMN IF NOT EXISTS tags TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS address_link VARCHAR(1024);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS contact TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS images TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS min_price DECIMAL(10, 2);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS max_price DECIMAL(10, 2);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS amenities TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS check_in_time VARCHAR(50);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS check_out_time VARCHAR(50);
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS cancellation_policy TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS child_policy TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS pet_policy TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS external_booking_links TEXT;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS views_count BIGINT DEFAULT 0;
ALTER TABLE hotels ADD COLUMN IF NOT EXISTS favorites_count INT DEFAULT 0;
