ALTER TABLE destinations ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE destinations ADD CONSTRAINT IF NOT EXISTS destinations_slug_unique UNIQUE(slug);

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS address VARCHAR(512);
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS tags TEXT;
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS best_time_to_visit VARCHAR(255);
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS opening_hours VARCHAR(255);

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS price_from DECIMAL(10, 2);
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS price_to DECIMAL(10, 2);

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS external_links TEXT;
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS address_link VARCHAR(1024);

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS avg_rating DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS review_count INT DEFAULT 0;
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS views_count BIGINT DEFAULT 0;
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS favorites_count INT DEFAULT 0;

-- STATUS: emulate MySQL ENUM with VARCHAR + CHECK constraint
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE destinations ADD CONSTRAINT IF NOT EXISTS chk_destinations_status
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'DRAFT'));

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;

-- Timestamps
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE destinations ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
